# Generated by Django 5.1.2 on 2024-12-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
